title = "Notre-Dame de Paris"
baseURL = "https://gohugo-theme-ananke.pages.dev"
languageCode = "en-us"
theme = ["hugo-shortcode-roneo-collection", "ananke"]
resourceDir = "../resources"

defaultContentLanguage = "en"
sectionPagesMenu = "main"
enableRobotsTXT = true

og_image = "img/pssra-logo-200.png"


[services.googleAnalytics]
id = ''

[pagination]
pagerSize = 3 # this is set low for demonstrating with dummy content. Set to a higher number

[languages.en]
contentDir = "content"
languageCode = 'en-US'
weight = 1
title = "Puget Sound SRA"


[sitemap]
changefreq = "monthly"
priority = 0.5
filename = "sitemap.xml"

[params]
mainSections = ["post"]
text_color = "mid-gray"
author = "Emma Goldman" # default author, override via `author` in a posts front matter
favicon = "favicon.ico"
site_logo = "img/pssra-logo-200.png"
featured_image = "img/Rainier20200906.jpg"
description = "Puget Sound Socialist Rifle Association, a Washington State chapter of the Socialist Rifle Association"
# choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
background_color_class = "bg-black"
# choose fitting and alignment styles for the featured image using Tachyons classes such as "cover|contain" for fitting and "bg-top|bg-center|bg-bottom" for alignment, or add any other class space-separated to customize further
featured_image_class = "cover bg-top"
# choose a color dimming class for the page or site header from any on this page: https://tachyons.io/docs/themes/skins/, preface it with "bg-" and add the value such as "-X0" where X is in [1,9]
cover_dimming_class = "bg-black-70"
recent_posts_number = 3
body_classes = "avenir bg-near-white"



[params.ananke.social.follow]
networks = [
  "bluesky",
  "instagram",
  "facebook",
  "twitter",
]

[params.ananke.social.bluesky]
username = "pugetsoundsra.org"

[params.ananke.social.instagram]
username = "pugetsoundsra"

[params.ananke.social.facebook]
username = "SeattleSRA"


[params.ananke.social.twitter]
username = "pugetsoundsra"


[caches]
  [caches.images]
    dir = ':cacheDir/images'

